-- ============================================================================
-- order-service schema (order_db)
-- ============================================================================

-- ── sku: a tiny static product catalog ─────────────────────────────────────
-- order-service reads price/name from here to SNAPSHOT them onto each order.
-- (A real system would have a product service; that is deliberately out of scope.)
CREATE TABLE sku (
    id         BIGINT        PRIMARY KEY,
    name       VARCHAR(200)  NOT NULL,
    price      NUMERIC(12,2) NOT NULL,           -- money is NUMERIC, never float
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ── orders: the order aggregate root ────────────────────────────────────────
CREATE TABLE orders (
    id           UUID          PRIMARY KEY,       -- UUID v7, generated by the app (time-ordered)
    order_no     VARCHAR(32)   NOT NULL UNIQUE,   -- human-facing order number
    user_id      BIGINT        NOT NULL,
    status       VARCHAR(20)   NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    currency     CHAR(3)       NOT NULL DEFAULT 'CNY',
    expire_at    TIMESTAMPTZ   NOT NULL,          -- payment deadline; drives timeout scan
    fail_reason  VARCHAR(64),
    version      INT           NOT NULL DEFAULT 0,-- optimistic-lock column (used later)
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT chk_orders_status
        CHECK (status IN ('CREATING','PENDING_PAYMENT','PAID','CANCELLED','FAILED'))
);

-- ★ Partial index: only PENDING_PAYMENT rows are indexed. The timeout scanner
--   queries exactly this slice, which is a tiny fraction of all orders. Paid /
--   cancelled orders drop OUT of the index automatically, so it stays small and
--   the scan cost is roughly constant regardless of total order volume.
CREATE INDEX idx_orders_timeout ON orders (expire_at)
    WHERE status = 'PENDING_PAYMENT';

-- Supports keyset pagination of a user's orders (ORDER BY created_at DESC, id DESC).
CREATE INDEX idx_orders_user ON orders (user_id, created_at DESC, id DESC);

-- ── order_items: order lines, with a price/name SNAPSHOT ────────────────────
-- ★ sku_name / unit_price are copied in on purpose. An order is a signed
--   contract: later price changes or renames must NOT alter historical orders.
--   This also makes reading an order a single-DB query (no call to inventory).
CREATE TABLE order_items (
    id         BIGSERIAL     PRIMARY KEY,
    order_id   UUID          NOT NULL REFERENCES orders(id),
    sku_id     BIGINT        NOT NULL,
    sku_name   VARCHAR(200)  NOT NULL,            -- snapshot
    unit_price NUMERIC(12,2) NOT NULL,            -- snapshot
    quantity   INT           NOT NULL CHECK (quantity > 0)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- ── idempotency: exactly-once guard for POST /orders ────────────────────────
-- ★ Idempotency is enforced by PRIMARY KEY conflict on insert, not by a
--   read-then-check (which would be a race). request_hash rejects reuse of the
--   same key with a different body.
CREATE TABLE idempotency (
    idem_key     VARCHAR(64) PRIMARY KEY,
    request_hash VARCHAR(64) NOT NULL,
    status       VARCHAR(16) NOT NULL
                 CHECK (status IN ('IN_PROGRESS','COMPLETED')),
    response     JSONB,                            -- cached first response
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── outbox: transactional outbox for reliable event publishing ──────────────
-- Written in the SAME local transaction as the order state change, so
-- "order committed" <=> "event will be delivered" (at-least-once).
CREATE TABLE outbox (
    id            BIGSERIAL   PRIMARY KEY,
    aggregate_id  UUID        NOT NULL,            -- order id; also the Kafka partition key
    event_type    VARCHAR(50) NOT NULL,
    payload       JSONB       NOT NULL,
    status        VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                  CHECK (status IN ('PENDING','SENT','DEAD')),
    retry_count   INT         NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NOT NULL DEFAULT now(),  -- exponential backoff
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ
);
-- Partial index: the relay only ever scans PENDING rows due for retry.
CREATE INDEX idx_outbox_pending ON outbox (next_retry_at)
    WHERE status = 'PENDING';

-- ── payment_anomaly: audit trail for suspicious/unmatched payment callbacks ─
CREATE TABLE payment_anomaly (
    id          BIGSERIAL   PRIMARY KEY,
    order_id    UUID,
    pay_no      VARCHAR(64),
    amount      NUMERIC(12,2),
    reason      VARCHAR(64) NOT NULL,             -- ORDER_NOT_FOUND / AMOUNT_MISMATCH / ...
    raw_payload JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── pending_refund: "paid but order already cancelled" needs a refund ───────
CREATE TABLE pending_refund (
    id         BIGSERIAL     PRIMARY KEY,
    order_id   UUID          NOT NULL,
    pay_no     VARCHAR(64)   NOT NULL,
    amount     NUMERIC(12,2) NOT NULL,
    status     VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);
